"use client"

import React, { createContext, useContext, useState, useCallback, type ReactNode } from "react"

export type Language = "en" | "fr" | "es" | "pt" | "ar" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.projects": "Projects",
    "nav.about": "About Us",
    "nav.blog": "Blog",
    "nav.contact": "Contact Us",
    "nav.quote": "Get A Quote",
    "hero.tag": "Crafting Digital Excellence",
    "hero.title1": "Building Digital Experiences That",
    "hero.title2": "Drive Growth",
    "hero.desc": "Sapwebs delivers reliable, scalable, and user-focused web solutions designed to help businesses thrive in a digital world.",
    "hero.cta1": "Get Started",
    "hero.cta2": "View Our Projects",
    "about.tag": "About Us",
    "about.title": "Empowering Your Success with Digital Expertise",
    "about.desc1": "Sapwebs is a professional web solutions brand specializing in the design, development, and deployment of high-quality digital platforms. We work with individuals, startups, SMEs, and organizations to transform ideas into impactful online experiences.",
    "about.desc2": "Our approach is collaborative, inclusive, and results-oriented -- ensuring every solution aligns with our clients' goals, users' needs, and industry best practices.",
    "about.why": "Why Choose Sapwebs",
    "about.v1": "Professional and scalable solutions",
    "about.v2": "Modern, responsive, and secure designs",
    "about.v3": "Clear communication and timely delivery",
    "about.v4": "Long-term support and maintenance",
    "about.v5": "Cost-effective development strategies",
    "about.btn": "About Us",
    "about.stat1": "Successful Projects",
    "about.stat2": "Expert Team",
    "about.stat3": "Happy Clients",
    "about.stat4": "Years of Experience",
    "services.tag": "Our Services",
    "services.title": "Boost Your Brand with Our Expertise",
    "services.desc": "Sapwebs offers a wide range of web and digital solutions tailored to meet diverse business needs.",
    "services.btn": "View All Services",
    "services.s1.title": "Web Design & Development",
    "services.s1.desc": "We create responsive, visually appealing, and high-performance websites using modern frameworks and best practices.",
    "services.s2.title": "E-Commerce Platforms",
    "services.s2.desc": "Secure and scalable e-commerce platforms that enhance online sales, with payment gateway integration and order tracking.",
    "services.s3.title": "Mobile Application Development",
    "services.s3.desc": "Native and cross-platform mobile apps for iOS and Android with intuitive interfaces and optimal performance.",
    "services.s4.title": "UI/UX Design",
    "services.s4.desc": "Beautiful, user-centered interface design and comprehensive user experience strategy for digital products.",
    "services.s5.title": "SEO Optimization",
    "services.s5.desc": "Comprehensive SEO strategies to boost online visibility, drive organic traffic, and rank higher on search engines.",
    "services.s6.title": "Website Maintenance",
    "services.s6.desc": "Ongoing support, updates, security monitoring, and performance optimization for your digital assets.",
    "services.learn": "Learn more",
    "portfolio.title": "Our Projects",
    "portfolio.desc": "We take pride in delivering solutions that meet real-world business challenges. Each project reflects our commitment to quality, functionality, and user experience.",
    "testimonials.title": "What Our Clients Say",
    "testimonials.desc": "We combine technical expertise, strategic thinking, and creative design to build websites and digital platforms that are not only visually appealing but also functional, secure, and performance-driven.",
    "contact.title": "Get in Touch",
    "contact.desc": "We're ready to discuss your project and bring your ideas to life. Contact us today and let's build something great together.",
    "contact.form.title": "Send us a Message",
    "contact.form.desc": "Fill out the form below and we will get back to you within 24 hours.",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email Address",
    "contact.form.phone": "Phone Number (Optional)",
    "contact.form.service": "Service Interested In",
    "contact.form.message": "Project Description",
    "contact.form.btn": "Send Message",
    "contact.form.submit": "Send Message",
    "contact.form.sending": "Sending...",
    "footer.newsletter": "Subscribe to Our Newsletter",
    "footer.newsletter.desc": "Stay updated with our latest news and offers",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.projects": "Projets",
    "nav.about": "A Propos",
    "nav.blog": "Blog",
    "nav.contact": "Nous Contacter",
    "nav.quote": "Devis Gratuit",
    "hero.tag": "Excellence Digitale",
    "hero.title1": "Construire des Experiences Digitales Qui",
    "hero.title2": "Stimulent la Croissance",
    "hero.desc": "Sapwebs fournit des solutions web fiables, evolutives et centrees sur l'utilisateur pour aider les entreprises a prosperer dans un monde numerique.",
    "hero.cta1": "Commencer",
    "hero.cta2": "Voir Nos Projets",
    "about.tag": "A Propos",
    "about.title": "Renforcer Votre Succes avec l'Expertise Digitale",
    "about.desc1": "Sapwebs est une marque professionnelle de solutions web specialisee dans la conception, le developpement et le deploiement de plateformes numeriques de haute qualite.",
    "about.desc2": "Notre approche est collaborative, inclusive et orientee resultats -- garantissant que chaque solution s'aligne avec les objectifs de nos clients.",
    "about.why": "Pourquoi Choisir Sapwebs",
    "about.v1": "Solutions professionnelles et evolutives",
    "about.v2": "Designs modernes, responsifs et securises",
    "about.v3": "Communication claire et livraison ponctuelle",
    "about.v4": "Support et maintenance a long terme",
    "about.v5": "Strategies de developpement rentables",
    "about.btn": "A Propos",
    "about.stat1": "Projets Reussis",
    "about.stat2": "Equipe d'Experts",
    "about.stat3": "Clients Satisfaits",
    "about.stat4": "Annees d'Experience",
    "services.tag": "Nos Services",
    "services.title": "Boostez Votre Marque avec Notre Expertise",
    "services.desc": "Sapwebs offre une large gamme de solutions web et digitales adaptees aux besoins divers des entreprises.",
    "services.btn": "Voir Tous les Services",
    "services.s1.title": "Conception & Developpement Web",
    "services.s1.desc": "Nous creons des sites web responsifs, visuellement attrayants et performants en utilisant des frameworks modernes.",
    "services.s2.title": "Plateformes E-Commerce",
    "services.s2.desc": "Plateformes e-commerce securisees et evolutives avec integration de paiement et suivi des commandes.",
    "services.s3.title": "Developpement d'Applications Mobiles",
    "services.s3.desc": "Applications mobiles natives et multi-plateformes pour iOS et Android avec des interfaces intuitives et performances optimales.",
    "services.s4.title": "Conception UI/UX",
    "services.s4.desc": "Conception d'interface belle et centree sur l'utilisateur avec une strategie d'experience utilisateur complete.",
    "services.s5.title": "Optimisation SEO",
    "services.s5.desc": "Strategies SEO completes pour augmenter la visibilite en ligne et ameliorer le classement dans les moteurs de recherche.",
    "services.s6.title": "Maintenance de Site Web",
    "services.s6.desc": "Support continu, mises a jour, surveillance de la securite et optimisation des performances pour vos actifs numeriques.",
    "services.learn": "En savoir plus",
    "portfolio.title": "Nos Projets",
    "portfolio.desc": "Nous sommes fiers de fournir des solutions qui repondent aux defis commerciaux reels.",
    "testimonials.title": "Ce Que Disent Nos Clients",
    "testimonials.desc": "Nous combinons expertise technique, reflexion strategique et design creatif pour construire des plateformes digitales.",
    "contact.title": "Contactez-Nous",
    "contact.desc": "Nous sommes prets a discuter de votre projet. Contactez-nous aujourd'hui.",
    "contact.form.title": "Envoyez-nous un Message",
    "contact.form.desc": "Remplissez le formulaire ci-dessous et nous vous repondrons dans les 24 heures.",
    "contact.form.name": "Nom Complet",
    "contact.form.email": "Adresse Email",
    "contact.form.phone": "Telephone (Optionnel)",
    "contact.form.service": "Service Interesse",
    "contact.form.message": "Description du Projet",
    "contact.form.btn": "Envoyer",
    "contact.form.submit": "Envoyer",
    "contact.form.sending": "Envoi...",
    "footer.newsletter": "Abonnez-vous a Notre Newsletter",
    "footer.newsletter.desc": "Restez informe de nos dernieres nouvelles et offres",
  },
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.portfolio": "Portafolio",
    "nav.projects": "Proyectos",
    "nav.about": "Nosotros",
    "nav.blog": "Blog",
    "nav.contact": "Contáctanos",
    "nav.quote": "Cotizacion",
    "hero.tag": "Excelencia Digital",
    "hero.title1": "Construyendo Experiencias Digitales Que",
    "hero.title2": "Impulsan el Crecimiento",
    "hero.desc": "Sapwebs ofrece soluciones web confiables, escalables y centradas en el usuario para ayudar a las empresas a prosperar en un mundo digital.",
    "hero.cta1": "Comenzar",
    "hero.cta2": "Ver Nuestros Proyectos",
    "about.tag": "Nosotros",
    "about.title": "Impulsando Tu Exito con Experiencia Digital",
    "about.desc1": "Sapwebs es una marca profesional de soluciones web especializada en el diseno, desarrollo e implementacion de plataformas digitales de alta calidad.",
    "about.desc2": "Nuestro enfoque es colaborativo, inclusivo y orientado a resultados.",
    "about.why": "Por Que Elegir Sapwebs",
    "about.v1": "Soluciones profesionales y escalables",
    "about.v2": "Disenos modernos, responsivos y seguros",
    "about.v3": "Comunicacion clara y entrega puntual",
    "about.v4": "Soporte y mantenimiento a largo plazo",
    "about.v5": "Estrategias de desarrollo rentables",
    "about.btn": "Nosotros",
    "about.stat1": "Proyectos Exitosos",
    "about.stat2": "Equipo Experto",
    "about.stat3": "Clientes Felices",
    "about.stat4": "Anos de Experiencia",
    "services.tag": "Nuestros Servicios",
    "services.title": "Impulsa Tu Marca con Nuestra Experiencia",
    "services.desc": "Sapwebs ofrece una amplia gama de soluciones web y digitales adaptadas a diversas necesidades empresariales.",
    "services.btn": "Ver Todos los Servicios",
    "services.s1.title": "Diseno & Desarrollo Web",
    "services.s1.desc": "Creamos sitios web responsivos, atractivos y de alto rendimiento utilizando frameworks modernos.",
    "services.s2.title": "Plataformas E-Commerce",
    "services.s2.desc": "Plataformas de comercio electronico seguras y escalables con integracion de pasarela de pago.",
    "services.s3.title": "Desarrollo de Aplicaciones Moviles",
    "services.s3.desc": "Aplicaciones moviles nativas y multiplataforma para iOS y Android con interfaces intuitivas y rendimiento optimo.",
    "services.s4.title": "Diseno UI/UX",
    "services.s4.desc": "Diseno de interfaz hermoso y centrado en el usuario con estrategia integral de experiencia del usuario.",
    "services.s5.title": "Optimizacion SEO",
    "services.s5.desc": "Estrategias SEO completas para aumentar la visibilidad en linea y mejorar el ranking en motores de busqueda.",
    "services.s6.title": "Mantenimiento de Sitios Web",
    "services.s6.desc": "Soporte continuo, actualizaciones, monitoreo de seguridad y optimizacion de rendimiento para sus activos digitales.",
    "services.learn": "Saber mas",
    "portfolio.title": "Nuestros Proyectos",
    "portfolio.desc": "Nos enorgullecemos de entregar soluciones que enfrentan desafios comerciales reales.",
    "testimonials.title": "Lo Que Dicen Nuestros Clientes",
    "testimonials.desc": "Combinamos experiencia tecnica, pensamiento estrategico y diseno creativo.",
    "contact.title": "Contactanos",
    "contact.desc": "Estamos listos para discutir tu proyecto. Contactanos hoy.",
    "contact.form.title": "Envianos un Mensaje",
    "contact.form.desc": "Completa el formulario y te responderemos en 24 horas.",
    "contact.form.name": "Nombre Completo",
    "contact.form.email": "Correo Electronico",
    "contact.form.phone": "Telefono (Opcional)",
    "contact.form.service": "Servicio de Interes",
    "contact.form.message": "Descripcion del Proyecto",
    "contact.form.btn": "Enviar Mensaje",
    "contact.form.submit": "Enviar Mensaje",
    "contact.form.sending": "Enviando...",
    "footer.newsletter": "Suscribete a Nuestro Boletin",
    "footer.newsletter.desc": "Mantente actualizado con nuestras ultimas noticias y ofertas",
  },
  pt: {
    "nav.home": "Inicio",
    "nav.services": "Servicos",
    "nav.portfolio": "Portfólio",
    "nav.projects": "Projetos",
    "nav.about": "Sobre Nos",
    "nav.blog": "Blog",
    "nav.contact": "Entre em Contato",
    "nav.quote": "Orcamento",
    "hero.tag": "Excelencia Digital",
    "hero.title1": "Construindo Experiencias Digitais Que",
    "hero.title2": "Impulsionam o Crescimento",
    "hero.desc": "A Sapwebs oferece solucoes web confiaveis, escalaveis e focadas no usuario para ajudar empresas a prosperar no mundo digital.",
    "hero.cta1": "Comecar",
    "hero.cta2": "Ver Nossos Projetos",
    "about.tag": "Sobre Nos",
    "about.title": "Fortalecendo Seu Sucesso com Experiencia Digital",
    "about.desc1": "A Sapwebs e uma marca profissional de solucoes web especializada no design, desenvolvimento e implantacao de plataformas digitais de alta qualidade.",
    "about.desc2": "Nossa abordagem e colaborativa, inclusiva e orientada a resultados.",
    "about.why": "Por Que Escolher a Sapwebs",
    "about.v1": "Solucoes profissionais e escalaveis",
    "about.v2": "Designs modernos, responsivos e seguros",
    "about.v3": "Comunicacao clara e entrega pontual",
    "about.v4": "Suporte e manutencao a longo prazo",
    "about.v5": "Estrategias de desenvolvimento rentaveis",
    "about.btn": "Sobre Nos",
    "about.stat1": "Projetos Bem-sucedidos",
    "about.stat2": "Equipe Especialista",
    "about.stat3": "Clientes Satisfeitos",
    "about.stat4": "Anos de Experiencia",
    "services.tag": "Nossos Servicos",
    "services.title": "Impulsione Sua Marca com Nossa Experiencia",
    "services.desc": "A Sapwebs oferece uma ampla gama de solucoes web e digitais adaptadas as diversas necessidades empresariais.",
    "services.btn": "Ver Todos os Servicos",
    "services.s1.title": "Design & Desenvolvimento Web",
    "services.s1.desc": "Criamos sites responsivos, visualmente atraentes e de alto desempenho usando frameworks modernos.",
    "services.s2.title": "Plataformas E-Commerce",
    "services.s2.desc": "Plataformas de e-commerce seguras e escalaveis com integracao de gateway de pagamento.",
    "services.s3.title": "Desenvolvimento de Aplicacoes Moveis",
    "services.s3.desc": "Aplicacoes moveis nativas e multiplataforma para iOS e Android com interfaces intuitivas e desempenho ideal.",
    "services.s4.title": "Design UI/UX",
    "services.s4.desc": "Design de interface bonito e centrado no usuario com estrategia completa de experiencia do usuario.",
    "services.s5.title": "Otimizacao SEO",
    "services.s5.desc": "Estrategias SEO completas para aumentar a visibilidade online e melhorar o ranking nos motores de busca.",
    "services.s6.title": "Manutencao de Site",
    "services.s6.desc": "Suporte continu, atualizacoes, monitoramento de seguranca e otimizacao de desempenho para seus ativos digitais.",
    "services.learn": "Saiba mais",
    "portfolio.title": "Nossos Projetos",
    "portfolio.desc": "Temos orgulho de entregar solucoes que enfrentam desafios empresariais reais.",
    "testimonials.title": "O Que Dizem Nossos Clientes",
    "testimonials.desc": "Combinamos experiencia tecnica, pensamento estrategico e design criativo.",
    "contact.title": "Entre em Contato",
    "contact.desc": "Estamos prontos para discutir seu projeto. Entre em contato hoje.",
    "contact.form.title": "Envie-nos uma Mensagem",
    "contact.form.desc": "Preencha o formulario e responderemos em 24 horas.",
    "contact.form.name": "Nome Completo",
    "contact.form.email": "Endereco de Email",
    "contact.form.phone": "Telefone (Opcional)",
    "contact.form.service": "Servico de Interesse",
    "contact.form.message": "Descricao do Projeto",
    "contact.form.btn": "Enviar Mensagem",
    "contact.form.submit": "Enviar Mensagem",
    "contact.form.sending": "Enviando...",
    "footer.newsletter": "Assine Nossa Newsletter",
    "footer.newsletter.desc": "Fique atualizado com nossas ultimas noticias e ofertas",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.services": "الخدمات",
    "nav.portfolio": "المحفظة",
    "nav.projects": "المشاريع",
    "nav.about": "من نحن",
    "nav.blog": "مدونة",
    "nav.contact": "اتصل بنا الآن",
    "nav.quote": "طلب عرض سعر",
    "hero.tag": "صناعة التميز الرقمي",
    "hero.title1": "بناء تجارب رقمية",
    "hero.title2": "تدفع النمو",
    "hero.desc": "سابويبز تقدم حلول ويب موثوقة وقابلة للتطوير ومركزة على المستخدم لمساعدة الشركات على الازدهار في العالم الرقمي.",
    "hero.cta1": "ابدأ الآن",
    "hero.cta2": "عرض مشاريعنا",
    "about.tag": "من نحن",
    "about.title": "تعزيز نجاحك بالخبرة الرقمية",
    "about.desc1": "سا��ويبز هي علامة تجارية متخصصة في تصميم وتطوير ونشر المنصات الرقمية عالية الجودة.",
    "about.desc2": "نهجنا تعاوني وشامل وموجه نحو النتائج.",
    "about.why": "لماذا تختار سابويبز",
    "about.v1": "حلول احترافية وقابلة للتطوير",
    "about.v2": "تصاميم حديثة ومتجاوبة وآمنة",
    "about.v3": "تواصل واضح وتسليم في الوقت المحدد",
    "about.v4": "دعم وصيانة طويلة الأمد",
    "about.v5": "استراتيجيات تطوير فعالة من حيث التكلفة",
    "about.btn": "من نحن",
    "about.stat1": "مشروع ناجح",
    "about.stat2": "فريق خبراء",
    "about.stat3": "عملاء سعداء",
    "about.stat4": "س��وات خبرة",
    "services.tag": "خدماتنا",
    "services.title": "عزز علامتك التجارية مع خبرتنا",
    "services.desc": "سابويبز تقدم مجموعة واسعة من الحلول الرقمية المصممة لتلبية احتياجات الأعمال المتنوعة.",
    "services.btn": "عرض جميع الخدمات",
    "services.s1.title": "تصميم وتطوير الويب",
    "services.s1.desc": "نقوم بإنشاء مواقع ويب متجاوبة وجذابة وعالية الأداء باستخدام أطر عمل حديثة.",
    "services.s2.title": "منصات التجارة الإلكترونية",
    "services.s2.desc": "منصات تجارة إلكترونية آمنة وقابلة للتطوير مع تكامل بوابات الدفع.",
    "services.s3.title": "تطوير تطبيقات الجوال",
    "services.s3.desc": "تطبيقات جوال أصلية وعبر منصات لنظامي iOS و Android مع واجهات بديهية وأداء مثالي.",
    "services.s4.title": "تصميم واجهة المستخدم/تجربة المستخدم",
    "services.s4.desc": "تصميم واجهة جميلة وموجهة للمستخدم مع استراتيجية تجربة مستخدم شاملة.",
    "services.s5.title": "تحسين محركات البحث",
    "services.s5.desc": "استراتيجيات SEO شاملة لزيادة الرؤية عبر الإنترنت وتحسين الترتيب في محركات البحث.",
    "services.s6.title": "صيانة الموقع",
    "services.s6.desc": "الدعم المستمر والتحديثات ومراقبة الأمان وتحسين الأداء لمواردك الرقمية.",
    "services.learn": "اعرف المزيد",
    "portfolio.title": "مشاريعنا",
    "portfolio.desc": "نفخر بتقديم حلول تواجه تحديات الأعمال الحقيقية.",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "testimonials.desc": "نجمع بين الخبرة التقنية والتفكير الاستراتيجي والتصميم الإبداعي.",
    "contact.title": "تواصل معنا",
    "contact.desc": "نحن مستعدون لمناقشة مشروعك. تواصل معنا اليوم.",
    "contact.form.title": "أرسل لنا رسالة",
    "contact.form.desc": "املأ النموذج أدناه وسنرد عليك خلال 24 ساعة.",
    "contact.form.name": "الاسم الكامل",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.phone": "رقم الهاتف (اختياري)",
    "contact.form.service": "الخدمة المطلوبة",
    "contact.form.message": "وصف المشروع",
    "contact.form.btn": "إرسال",
    "contact.form.submit": "إرسال",
    "contact.form.sending": "جاري الإرسال...",
    "footer.newsletter": "اشترك في نشرتنا الإخبارية",
    "footer.newsletter.desc": "ابق على اطلاع بأحدث أخبارنا وعروضنا",
  },
  zh: {
    "nav.home": "首页",
    "nav.services": "服务",
    "nav.portfolio": "作品集",
    "nav.projects": "项目",
    "nav.about": "关于我们",
    "nav.blog": "博客",
    "nav.contact": "联系我们",
    "nav.quote": "获取报价",
    "hero.tag": "打造数字卓越",
    "hero.title1": "构建推动增长的",
    "hero.title2": "数字体验",
    "hero.desc": "Sapwebs提供可靠、可扩展且以用户为中心的网络解决方案，帮助企业在数字世界中蓬勃发展。",
    "hero.cta1": "开始使用",
    "hero.cta2": "查看我们的项目",
    "about.tag": "关于我们",
    "about.title": "用数字专业知识助力您的成功",
    "about.desc1": "Sapwebs是一个专业的网络解决方案品牌，专注于高质量数字平台的设计、开发和部署。",
    "about.desc2": "我们的方法是协作、包容和以结果为导向的。",
    "about.why": "为什么选择Sapwebs",
    "about.v1": "专业且可扩展的解决方案",
    "about.v2": "现代、响应式且安全的设计",
    "about.v3": "清晰的沟通和及时的交付",
    "about.v4": "长期支持和维护",
    "about.v5": "性价比高的开发策略",
    "about.btn": "关于我们",
    "about.stat1": "成功项目",
    "about.stat2": "专家团队",
    "about.stat3": "满意客户",
    "about.stat4": "年经验",
    "services.tag": "我们的服务",
    "services.title": "用我们的专业知识提升您的品牌",
    "services.desc": "Sapwebs提供广泛的网络和数字解决方案，以满足各种业务需求。",
    "services.btn": "查看所有服务",
    "services.s1.title": "网页设计与开发",
    "services.s1.desc": "我们使用现代框架创建响应式、视觉吸引力强且高性能的网站。",
    "services.s2.title": "电子商务平台",
    "services.s2.desc": "安全且可扩展的电子商务平台，集成支付网关和订单跟踪。",
    "services.s3.title": "移动应用开发",
    "services.s3.desc": "为iOS和Android提供的原生和跨平台移动应用，具有直观界面和最佳性能。",
    "services.s4.title": "UI/UX设计",
    "services.s4.desc": "美观的用户中心界面设计和全面的用户体验策略，适用于数字产品。",
    "services.s5.title": "SEO优化",
    "services.s5.desc": "全面的SEO策略，提高在线可见性，增加有机流量，提高搜索引擎排名。",
    "services.s6.title": "网站维护",
    "services.s6.desc": "为您的数字资产提供持续支持、更新、安全监控和性能优化。",
    "services.learn": "了解更多",
    "portfolio.title": "我们的项目",
    "portfolio.desc": "我们为提供满足现实商业挑战的解决方案而自豪。",
    "testimonials.title": "客户评价",
    "testimonials.desc": "我们将技术专长、战略思维和创意设计相结合。",
    "contact.title": "联系我们",
    "contact.desc": "我们已准备好讨论您的项目。今天就联系我们。",
    "contact.form.title": "给我们留言",
    "contact.form.desc": "填写下面的表单，我们将在24小时内回复您。",
    "contact.form.name": "全名",
    "contact.form.email": "电子邮件",
    "contact.form.phone": "电话（可选）",
    "contact.form.service": "感兴趣的服务",
    "contact.form.message": "项目描述",
    "contact.form.btn": "发送消息",
    "contact.form.submit": "发送消息",
    "contact.form.sending": "发送中...",
    "footer.newsletter": "订阅我们的新闻通讯",
    "footer.newsletter.desc": "及时了解我们的最新消息和优惠",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = useCallback(
    (key: string) => {
      return translations[language]?.[key] || translations.en[key] || key
    },
    [language]
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export const languageOptions: { code: Language; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "GB" },
  { code: "fr", label: "Francais", flag: "FR" },
  { code: "es", label: "Espanol", flag: "ES" },
  { code: "pt", label: "Portugues", flag: "PT" },
  { code: "ar", label: "العربية", flag: "SA" },
  { code: "zh", label: "中文", flag: "CN" },
]
